services:
  - type: web
    name: traductor-lsm
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run traductor_app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
